services:
  # Dockerを使用した統合デプロイ
  - type: web
    name: prompthub
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: node server.js
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false # Renderダッシュボードで設定
      - key: JWT_SECRET
        sync: false # Renderダッシュボードで設定
    autoDeploy: true