services:
  # Dockerではなく、ビルドパック（Node.js）を使用
  - type: web
    name: prompthub
    env: node
    region: singapore # 任意のリージョンを選択
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # Renderダッシュボードで設定
      - key: JWT_SECRET
        sync: false # Renderダッシュボードで設定
    autoDeploy: true