services:
  # 単一のサービスとしてバックエンドとフロントエンドを統合
  - type: web
    name: prompthub
    env: docker
    region: singapore # 任意のリージョンを選択
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false # Renderダッシュボードで設定
      - key: JWT_SECRET
        sync: false # Renderダッシュボードで設定
    autoDeploy: true